# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python27:
      python.version: '2.7'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    set -xe
    python --version
    python -m pip install --upgrade pip
    # disable builds isolation in pip to allow installing numba
    # for python 2.7
    python -m pip install --no-build-isolation -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    set -xe
    pip install -e .
  displayName: 'Install tslearn'

- script: |
    set -xe
    # avoid CPU oversubscription
    export OMP_NUM_THREADS=2
    export NUMBA_NUM_THREADS=2
    python -m pip install pytest pytest-azurepipelines pytest-timeout
    python -m pytest -v --durations 10 --timeout 90 tslearn/
  displayName: 'Test'
